- .gitignore
- queen-attack/example.cpp
- queen-attack/queen_attack_test.cpp
The unit tests and the example implementation test the north-west / south-east diagonal, but are missing the north-east / south-west diagonal.
Also there is no test case where the queens are _not_ attacking each other.
> queen-attack is missing tests (and example implementation) for the other diagonal

- binary/binary_test.cpp
Made this to make more clear how input shall be handled that looks valid right away from start but turns out to be invalid somewhere in the middle or the end.
The behaviour I test against should match the current behaviour of the reference-implementation. But perhaps we should require to `throw` something instead?
> Add testcase with invalid char at the end

- docs/TESTS.md
Hey there,
as the issue #52 asks, I added such information to the `TESTS.md` documentation. Is this what you had in mind, @LegalizeAdulthood?
> Added a statement to specify that building the code runs the tests.

- docs/INSTALLATION.md
A bulleted list in the [Installing C++](http://exercism.io/languages/cpp) page looks fine when rendered in GitHub as markdown, but I guess Redcarpet or something might be parsing/rendering slightly differently, because it shows up like this on the website:
> ![2016-02-14_7-15-38](https://cloud.githubusercontent.com/assets/124687/13033597/ea524de4-d2ea-11e5-8b3f-79aeabf2cd8f.png)
I am guessing that my fix will fix things but I didn't actually test it out.
> Hopefully fix formatting of bulleted list.

- docs/TESTS.md
They currently look as follows in the testing section of [C++ track doc](http://exercism.io/languages/cpp#tests):
> Once the build environment has been created by CMake, you can build your code using the appropriate command for your environment: * Linux with make: make * Windows with Visual Studio 2013: Select Build / Build Solution from the menu. * MacOS with Xcode: Select Build from the toolbar
instead of
> Once the build environment has been created by CMake, you can build your code using the appropriate command for your environment:
> * Linux with make: make
> * Windows with Visual Studio 2013: Select Build / Build Solution from the menu.
> * MacOS with Xcode: Select Build from the toolbar
> Fix markdown formatting of bullets

- SETUP.md
Closes https://github.com/exercism/xcpp/issues/73.
> Remove deprecated help.exercism.io links

- sum-of-multiples/example.cpp
- sum-of-multiples/example.h
- sum-of-multiples/sum_of_multiples_test.cpp
Updates the tests and example solution to require an explicit
declaration of multiples, matching the test cases from x-common/sum-of-multiples.json
To fix Issue #71
> sum-of-multiples: Removing implicit list of multiples

- robot-name/example.cpp
- robot-name/robot_name_test.cpp
Update robot-name to allow only uppercase letters. This keeps the xcpp
track updated with the current instructions. See exercism/x-common#283
> robot-name: Require uppercase letters

- exercises/anagram/anagram_test.cpp
This exercise is the first that requires the solver to define a class. This patch helps users who may be unfamiliar with the syntax determine what is required.
Learners (especially those new to programming or new to programming with classes) may have difficulty determining a class is required for the existing tests. This gives them something to google if they don't know what's going on.
Closes #98
> anagram: clarify solution requirements

- exercises/nucleotide-count/example.cpp
- exercises/nucleotide-count/nucleotide_count_test.cpp
Adds a test for invalid input in the constructor.
Closes #50.
> nucleotide-count: Throw exception on constructor

- exercises/etl/etl_test.cpp
Currently, first make of the problem "etl" fails because the etl_tests.cpp file uses std::map without including <map>. Adding #include <map> fixes it. (Another way to "fix" is to include map inside of etl.h, but that feels like a "hack". The unit tests should include type declarations for types it's using itself! :) )
> Let first 'make' fail for the right reason

- exercises/gigasecond/example.cpp
- exercises/gigasecond/example.h
- exercises/gigasecond/gigasecond_test.cpp
Update gigasecond exercise to use times instead of dates.
Closes #34
> gigasecond: use times (not dates)

- exercises/clock/clock_test.cpp
- exercises/clock/example.cpp
- exercises/clock/example.h
I updated the test suite for clock to match the new JSON, and fixed the example solution to work with it.
Because there are a _lot_ of test cases for clock, I copied how [the Go track handles the test cases](https://github.com/exercism/xgo/tree/master/exercises/clock), placing the test cases into a vector and iterating over them. This might make it a little difficult to tell which test case is failing, but I believe the Boost output messages handle it well enough.
This is different from all of the other test suites for the cpp track (I think), so it may require some review/rework.
Closes #78
> clock: Adding full test suite.

- exercises/grade-school/grade_school_test.cpp
- exercises/nucleotide-count/nucleotide_count_test.cpp
Added #include \<map\> to another two unit tests lacking it.
> Include map in two tests using map, but not including it

- README.md
- config.json
- docs/INSTALLATION.md
The leading 'x' is kind of arbitrary. Especially now that we can set
topics on the repositories, we don't need a pattern to distinguish what
is a track or not.
The repository itself has already been renamed. GitHub redirects from
the old name to the new name, so we do not have to rush to fix links to
the old repository name, though we should update them for the sake of
clarity.
See exercism/meta#1
> Remove leading 'x' from repository name

- CMakeLists.txt
- config.json
- exercises/atbash-cipher/CMakeLists.txt
- exercises/atbash-cipher/atbash_cipher_test.cpp
- exercises/atbash-cipher/example.cpp
- exercises/atbash-cipher/example.h
Here's a port of the atbash-cipher exercise. Was originally gonna do the example implementation with some tidy modern c++ std::erase_if and std::transform stuff until I realized it'd take 3 passes over the string, yuck. So, for-loops in 1 pass it is. Let me know if anything needs changed.
> Port atbash-cipher exercise

- docs/ABOUT.md
Hello :)
On nextercism the ABOUT.md is currently rendered like this:
I have removed line breaks and the double bullet points to make it look lots nicer. I have not edited the content itself. It will now render like this (the space on the right for the code snippet)
See https://github.com/exercism/meta/issues/84 for more details.
> Prepare ABOUT.md for nextercism

- exercises/gigasecond/gigasecond_test.cpp
As pointed out in #139, the template errors thrown by the gigasecond test if you have an incorrect return type can be _really_ bad. This just gives a hint to the correct return type to avoid that problem in the future.
Closes #139
> Clarify type of gigasecond return value to avoid template edgecase.

- exercises/crypto-square/crypto_square_test.cpp
- exercises/crypto-square/example.cpp
Updates the crypto-square test suite (and the example solution) to match the description and canonical json. See #97.
This new test suite is incompatible with the old solutions. I still need to look into whether this needs to be marked as v2 or something before merging it.
Closes #97
> Update crypto-square tests.

- docs/ABOUT.md
I've updated the about section to reference the current C++17 standard (it may be useful to reword this section completely in future to avoid needing to update this again).
[Issue #183]
> Updated ABOUT.md to include current standard

- exercises/meetup/meetup_test.cpp
This diff addresses the following issue where the tests assume the streaming operators will be included in `meetup.h`. We should not force this dependency on the user's code.
Clang++ `6.0.1`
Boost version: `1.67.0_1`
```
[ 33%] Building CXX object CMakeFiles/meetup.dir/meetup_test.cpp.o
In file included from /Users/collen/exercism/cpp/meetup/meetup_test.cpp:3:
In file included from /usr/local/include/boost/test/unit_test.hpp:18:
In file included from /usr/local/include/boost/test/test_tools.hpp:46:
In file included from /usr/local/include/boost/test/tools/old/impl.hpp:24:
/usr/local/include/boost/test/tools/detail/print_helper.hpp:52:13: error: static_assert failed due to requirement 'boost::has_left_shift<std::ostream,
date>::value' "Type has to implement operator<< to be printable" …
```
> Add missing include to "meetup" exercise test file

- exercises/gigasecond/gigasecond_test.cpp
I'm getting a compiler error when trying the gigasecond exercise.
The library needed for posit_time was missing.
Please check the boost documentations: http://www.boost.org/doc/libs/1_59_0/doc/html/date_time/posix_time.html
> Including needed boost::posix_time.h

- exercises/hello-world/README.md
The readme for the Hello World has a broken "installing" link n the ## Getting Started section
> Fix broken link in Hello World readme

- CMakeLists.txt
A full build skips the `hello-world` exercise entirely.
Is there any reason that we should avoid this exercise?
> Run tests on hello-world exercise

- exercises/difference-of-squares/difference_of_squares_test.cpp
- exercises/difference-of-squares/example.cpp
- exercises/difference-of-squares/example.h
In the exercise "difference-of-squares", I changed `square_of_sums` to `square_of_sum`.
This change is similar to the one done in the  [Haskell track](https://github.com/exercism/haskell/pull/711).
> difference-of-squares: Rename square_of_sums to square_of_sum

- exercises/triangle/example.cpp
- exercises/triangle/example.h
- exercises/triangle/triangle_test.cpp
I needed to put the `BOOST_TEST_DONT_PRINT_LOG_VALUE` as mentioned [here](https://stackoverflow.com/questions/30860241/use-enum-classes-with-boost-test).
The error messages are still readable and contain the actual expression.
This will break previous solutions.
> moved to use enum class

- exercises/space-age/space_age_test.cpp
All other math operators are surrounded by spaces. This one was missing a leading space.
> Surround math operator with space

- exercises/phone-number/example.cpp
- exercises/phone-number/phone_number_test.cpp
Current examples shouldn't pass the tests since the [problem spec](https://github.com/exercism/problem-specifications/blob/master/exercises/phone-number/canonical-data.json) changed. 
EDIT: forgot to mention this is for issue #227
> C++ phone number tests

- exercises/space-age/space_age_test.cpp
Move the declaration of the 'accuracy' variable inside the
EXERCISM_RUN_ALL_TESTS section, so that when compiling the first test
case, the unused variable warning wouldn't show up.
> Fix the unused variable warning in space age

- exercises/sieve/sieve_test.cpp
When the `limit` is a prime number, test if the answer includes the `limit`.
> Add more test cases in the sieve exercise

- exercises/leap/leap_test.cpp
Since I found a student's solution was using 200 instead of 400, I think this might be a common case.
The test code we are using now is largely different from the canonical test suite. Because that code base changes quite frequently, I kept our test code, adding only one extra test case which I think is needed. Would be glad to sync the whole test code from the canonical test data if that is desired.
> Update the test case in the leap exercise

- exercises/acronym/example.cpp
- exercises/anagram/example.cpp
- exercises/bob/example.cpp
- exercises/crypto-square/example.cpp
- exercises/word-count/example.cpp
Replaces boost/algorithm usage in the example solutions with code that only uses std.
Part of #233.
> Removing boost/algorithms in example solutions

- config.json
All this does is replace gigasecond with reverse-string in the core tracks, set gigasecond to be unlocked by reverse-string, and set all gigasecond dependent exercises to depend on reverse-string.
Part of #233 and #237 
This helps to visualize the track config: https://jonmcalder.shinyapps.io/exercism-config-viz/
> Swap out gigasecond for reverse-string in the core tracks.

- README.md
- docs/INSTALLATION.md
Adds a small note to the installation docs explaining that some tests may not use Boost, and a link to how people can track progress. This should be merged only when there are at least a couple problems setup with Catch.
This mostly serves as a note to people having issues with installing Boost to note we are working on it. If anyone has any input about how this could be better, or would like to point out something else we should say here, please let me know.
Related to #233
> Updating documentation to explain Boost deprecation.

- exercises/grains/CMakeLists.txt
- exercises/grains/grains_test.cpp
- exercises/grains/test/catch.hpp
- exercises/hello-world/CMakeLists.txt
- exercises/hello-world/hello_world_test.cpp
- exercises/hello-world/test/catch.hpp
- exercises/leap/CMakeLists.txt
- exercises/leap/leap_test.cpp
- exercises/leap/test/catch.hpp
- exercises/pangram/CMakeLists.txt
- exercises/pangram/pangram_test.cpp
- exercises/pangram/test/catch.hpp
- exercises/raindrops/CMakeLists.txt
- exercises/raindrops/raindrops_test.cpp
- exercises/raindrops/test/catch.hpp
- exercises/reverse-string/CMakeLists.txt
- exercises/reverse-string/reverse_string_test.cpp
- exercises/reverse-string/test/catch.hpp
- exercises/space-age/CMakeLists.txt
- exercises/space-age/space_age_test.cpp
- exercises/space-age/test/catch.hpp
- exercises/triangle/CMakeLists.txt
- exercises/triangle/test/catch.hpp
- exercises/triangle/triangle_test.cpp
Drops Boost for Catch 2.7.0 in the core exercises (after #240 is merged). Depends on #239 getting merged first.
Related to #233.
> Moving all the core exercises to Catch2.

- config.json
- exercises/binary-search-tree/CMakeLists.txt
- exercises/binary-search-tree/binary_search_tree_test.cpp
- exercises/binary-search-tree/test/catch.hpp
This moves the only tricky test suite over to Catch, specifically the iterator test in `test_sort()`. 
FYI - @elyashiv 
Related to #233, dependent on #244.
> binary-search-tree: Onboard to Catch2.

- config.json
This adds a test_pattern to config.json so that only the test suite shows up on exercism.io rather than the full copy of Catch.
> Adding test_pattern.

- exercises/acronym/CMakeLists.txt
- exercises/acronym/acronym_test.cpp
- exercises/acronym/test/catch.hpp
- exercises/all-your-base/CMakeLists.txt
- exercises/all-your-base/all_your_base_test.cpp
- exercises/all-your-base/test/catch.hpp
- exercises/binary/CMakeLists.txt
- exercises/binary/binary_test.cpp
- exercises/binary/test/catch.hpp
- exercises/hexadecimal/CMakeLists.txt
- exercises/hexadecimal/hexadecimal_test.cpp
- exercises/hexadecimal/test/catch.hpp
- exercises/isogram/CMakeLists.txt
- exercises/isogram/isogram_test.cpp
- exercises/isogram/test/catch.hpp
- exercises/pascals-triangle/CMakeLists.txt
- exercises/pascals-triangle/pascals_triangle_test.cpp
- exercises/pascals-triangle/test/catch.hpp
- exercises/robot-simulator/CMakeLists.txt
- exercises/robot-simulator/robot_simulator_test.cpp
- exercises/robot-simulator/test/catch.hpp
- exercises/scrabble-score/CMakeLists.txt
- exercises/scrabble-score/scrabble_score_test.cpp
- exercises/scrabble-score/test/catch.hpp
This converts every exercise that not a core exercise or dependent on one. These exercises are all available even before completing hello-world.
The conversions are all straightforward, nothing surprising. I'll merge these on April 13th unless there are objections (may take longer) or an LGTM from another set of eyes (maybe sooner).
See #253.
> Boost -> Catch: All no-dependency exercises.

- exercises/grade-school/CMakeLists.txt
- exercises/grade-school/grade_school_test.cpp
- exercises/grade-school/test/catch.hpp
- exercises/hamming/CMakeLists.txt
- exercises/hamming/hamming_test.cpp
- exercises/hamming/test/catch.hpp
- exercises/nucleotide-count/CMakeLists.txt
- exercises/nucleotide-count/nucleotide_count_test.cpp
- exercises/nucleotide-count/test/catch.hpp
- exercises/rna-transcription/CMakeLists.txt
- exercises/rna-transcription/rna_transcription_test.cpp
- exercises/rna-transcription/test/catch.hpp
See #253 for context.
grade-school needed a small tweak to handle the test fixture used in the old test. Catch could be configured to have the fixture as well, but it was just clearer to add it into each test.
I'll merge this on April 13th unless something comes up.
> Boost -> Catch: Everything unlocked by hello-world.

- exercises/food-chain/CMakeLists.txt
- exercises/food-chain/food_chain_test.cpp
- exercises/food-chain/test/catch.hpp
- exercises/phone-number/CMakeLists.txt
- exercises/phone-number/phone_number_test.cpp
- exercises/phone-number/test/catch.hpp
- exercises/roman-numerals/CMakeLists.txt
- exercises/roman-numerals/roman_numerals_test.cpp
- exercises/roman-numerals/test/catch.hpp
- exercises/series/CMakeLists.txt
- exercises/series/series_test.cpp
- exercises/series/test/catch.hpp
Will merge on April 20th barring any issues. Nothing too interesting in these.
See #253
> Boost -> Catch: Everything unlocked by grains.

- exercises/gigasecond/CMakeLists.txt
- exercises/gigasecond/gigasecond_test.cpp
- exercises/gigasecond/test/catch.hpp
- exercises/meetup/CMakeLists.txt
- exercises/meetup/meetup_test.cpp
- exercises/meetup/test/catch.hpp
These two exercises depend on Boost Date Time. I converted them to use Catch, but kept the dependency on Boost datetime.
These will require the installation of the Boost date_time library to use, but since they are not core exercises people can skip them if they have issues.
Will merge on April 20th unless something comes up.
See #253 for Catch info, and #224 for reasoning as to why date_time is still a dependency.
> Boost -> Catch: Gigasecond and Meetup

- README.md
- docs/INSTALLATION.md
- docs/TESTS.md
This is a decent sized doc update adding better Windows instructions and taking into account all the changes being made with the switch to Catch2.
I'll plan to merge this once all the exercises are updated, planned for April 20th.
Related to #233
> Boost->Catch: Final Docs update

- .travis.yml
- CMakeLists.txt
- bin/check-exercises.sh
- exercises/acronym/acronym_test.cpp
This switches the Travis builds so that it tests different subsets of the exercises depending on whether it is a PR build or a branch build, and on the changes made compared to the master branch. Basically, for a normal PR this will help lighten the load while it's being worked on, and we will run a full build against master once it is merged.
Some other tracks do this already, I've borrowed from the script used for Rust but heavily modified it.
If it's a branch build we run everything, as we currently do.
If it's a PR build that changes no exercises, we run nothing.
If it's a PR build that changes 1 or more exercises, _we only run the changed exercises._
If it's a PR build that changes the _root_ CMakeLists.txt file, we run everything to make sure that works. [1]
I'll be kicking off …
> Adding partial builds to Travis

- exercises/luhn/luhn_test.cpp
In version 1.6.0 of the canonical-data.json in the
problem-specifications repository a new test case was added.
This commit just incorporates that test into the C++ test suite.
> Luhn: Add a test with an odd number of spaces

- exercises/all-your-base/all_your_base_test.cpp
- exercises/all-your-base/example.cpp
Fixes #280 without modifying base 1 behavior. Fixes `leading_zeros` test case and requires `std::error` for test cases where the base is invalid.
> Fixes #280. Problem spec intact.

- config.json
- exercises/armstrong-numbers/CMakeLists.txt
- exercises/armstrong-numbers/README.md
- exercises/armstrong-numbers/armstrong_numbers_test.cpp
- exercises/armstrong-numbers/example.cpp
- exercises/armstrong-numbers/example.h
- exercises/armstrong-numbers/test/catch.hpp
- exercises/armstrong-numbers/test/tests-main.cpp
Hi!
Ported [armstrong-numbers](https://github.com/exercism/problem-specifications/tree/master/exercises/armstrong-numbers) exercise to C++.
> Implement armstrong numbers

- exercises/anagram/anagram_test.cpp
This should no longer allow weird solutions where the entire input is rejected if some of the anagram / original word input strings have different case to pass.
Original solution where this was noted: https://exercism.io/mentor/solutions/e4f49b89e76042c9b82544bcfca04929
> Anagram - modify test cases

- .gitignore
- .travis.yml
- bin/check-hello-world.sh
- exercises/hello-world/example.cpp
- exercises/hello-world/hello_world.cpp
- exercises/hello-world/hello_world.h
- exercises/hello-world/hello_world_test.cpp
Closes #273 
This adds lots of comments and a compilable example for the hello world exercise. It also adds a CI test to validate that assertion.
> Improves Hello-World

- exercises/word-count/word_count_test.cpp
Adds three test cases:
* substrings_from_the_beginning (exercism/problem-specifications#1557)
* multiple_spaces_not_detected_as_a_word (exercism/problem-specifications#1023)
* alternating_word_separators_not_detected_as_a_word (exercism/problem-specifications#1446)
> Word-count - update tests specification to version 1.4.0

- exercises/circular-buffer/circular_buffer_test.cpp
This adds a test case to Circular buffer, testing for a quite specific but important case when `circular_buffer::clear()` partially affects the use of the buffer.
In the solution where I came across this, the underlying `vector` was being `clear()`ed as well, preserving the allocated space while messing with the start and end iterators. This passed all the tests, however, as there was no test for `clear()` followed by `overwrite()` nor a failing `read()`.
[Link to the solution](https://exercism.io/mentor/solutions/dabad4b50b764378afb4e2cf976e584d?iteration_idx=2)
> Circular buffer - add test case for initial clear

- .github/workflows/ci.yml
- .github/workflows/hello-world.yml
- CMakeLists.txt
- bin/check-hello-world.sh
- exercises/armstrong-numbers/example.cpp
Replaces Travis CI with Github Actions. This change also adds testing on Windows and Mac in addition to Linux.
I could leave in Travis, but this change is already a super-set of Travis functionality.
> Use Github Actions for CI

- exercises/grade-school/grade_school_test.cpp
Currently school::roster() and school::grade() can be implemented as
non-const methods. Logically it makes sense to be able to call those two
methods on a const instance because they should not modify that
instance.
> grade-school: Force const on roster() and grade()

- exercises/gigasecond/README.md
- exercises/meetup/README.md
Gigasecond and Meetup use Boost libraries to handle time functions.
Warn students of this in the README.
> Add links to Boost libraries in exercise READMEs

- .travis.yml
- exercises/gigasecond/CMakeLists.txt
- exercises/gigasecond/README.md
- exercises/gigasecond/gigasecond_test.cpp
- exercises/meetup/CMakeLists.txt
- exercises/meetup/README.md
- exercises/meetup/meetup_test.cpp
This bump lets us test directly on our minimum supported version, and
removes the workarounds put in place for supporting Trusty (14.04)
Closes #323
> Bump Travis CI dist to Xenial (16.04)

- bin/fetch-configlet
https://github.com/exercism/configlet/issues/173: Travis CI are fails because of fetch-configlet script failure while getting latest release URL. As described in https://github.com/exercism/haskell/pull/898#pullrequestreview-368719612 the problem was that  `curl` started to output headers in lowercase
Few days ago I was created PR which simply fixed the case (https://github.com/exercism/cpp/pull/344)
This PR provides possibility to get latest release of configlet script using GitHub API.
> Modify fetch-configlet script

- .github/workflows/ci.yml
- bin/fetch-configlet
- bin/fetch-configlet.ps1
Updates our version of fetch-configlet to the latest version in the configlet repo. See https://github.com/exercism/configlet/pull/174 for context.
> fetch-configlet: Pull upstream changes.

- exercises/triangle/triangle_test.cpp
Some solutions use templates, and this test won't compile if they have just one template argument.
A sample compilation error:
no matching function for call to ‘kind(double, int, int)’
> Add test for double and integer argumetns

- exercises/binary-search-tree/example.h
Adds a missing include that is causing a test failure in the clang-latest tests.
> binary-search-tree: Add missing include.

- exercises/concept/strings/.meta/config.json
The authors and contributors of exercises are stored in an array of objects in the exercises' `.meta/config.json` files.
Each author/contributor used to have two properties: their GitHub username _and_ their Exercism username.
As we're only using the GitHub username, we're flattening the `authors` and `contributors` array to an array of strings representing the GitHub usernames.
We will update `configlet` to validate the new structure, so you might be seeing build failures once we've implemented this change. 
See https://github.com/exercism/docs/pull/90/files
We will automatically merge this PR immediately to be able to submit a different PR in which we'll add the authors/contributors for practice exercises.
https://github.com/exercism/v3-launch/issues/26
> 🤖 Flatten authors and contributors in .meta/config.json files

- concepts/strings/about.md
- concepts/strings/introduction.md
- docs/ABOUT.md
- docs/INSTALLATION.md
- docs/LEARNING.md
- docs/RESOURCES.md
- docs/TESTS.md
- exercises/concept/strings/.docs/after.md
- exercises/concept/strings/.docs/hints.md
- exercises/concept/strings/.docs/instructions.md
- exercises/concept/strings/.docs/introduction.md
- exercises/concept/strings/.meta/design.md
We've defined a [specification for Markdown files](https://github.com/exercism/docs/blob/main/contributing/standards/markdown.md) to be applied Exercism-wide. This standard includes, amongst others, the following two rules:
- All files must start start with a level-1 heading (`# Some heading text`)
- No heading may decend a level greater than one below the previous (e.g. `## may only be followed by ###, not ####`)
This PR applies the above two rules to the Markdown documents in this repo. 
https://github.com/exercism/v3-launch/issues/17
> [v3] Update Markdown files to latest spec

- .github/workflows/ci.yml
- CMakeLists.txt
- config.json
- exercises/concept/strings/.meta/config.json
Configlet lint was configured as a prerequisite for CI. It should instead just be an FYI, and checked manually on any PRs for changes to the config file.
It still runs as a separate Github Action "Configlet CI".
As this is fixing our CI pipeline, which will unblock other changes, if I can I will just approve and merge this myself once it passes.
Passes the current linting checks #422 
Closes #420.
> Removing configlet lint from critical CI path.

- exercises/practice/binary-search-tree/.meta/config.json
- exercises/practice/circular-buffer/.meta/config.json
- exercises/practice/hello-world/.meta/config.json
- exercises/practice/leap/.meta/config.json
- exercises/practice/meetup/.meta/config.json
- exercises/practice/two-fer/.meta/config.json
Closes #458
* Removes unused example.cpp files from the files array. Those exercises only use an `example.h` file for the example solution.
* Sets the header file for `hello-world` to the `hello_world.h` file, which is reused without modification for both the example solution and the skeleton for the students.
> Fix example solution lists

- exercises/practice/hello-world/.meta/config.json
Fixes #482 
The skeleton solution downloaded for the user needs to include hello_world.h, otherwise the student needs to create that file themselves.
As a sidenote, does anyone know if there is any documentation on what the fields in this json file actually do? I haven't been able to find any and am only assuming from context.
> Include hello_world.h as part of the solution

- .github/workflows/ci.yml
- docs/INSTALLATION.md
Closes #487 
Github Actions has already dropped support for Ubuntu 16.04. Our CI will not work without bumping the min version.
This just bumps the Min version to 18.04 without updating anything else, so that we can continue to test on our minimum supported version.
> Bump the Linux Min config version to Ubuntu 18.04.

- exercises/practice/hello-world/.meta/config.json
- exercises/practice/hello-world/.meta/example.h
Listing the `hello_world.h` file as an example file causes it to not be downloaded. This creates a copy of that file in the `.meta` directory to use as the example solution.
Fixes #482
See #484 for a previous attempt to fix issue #482, and discussion from @iHiD and @ErikSchierboom helping to diagnose the problem :)
> Split out example from hello_world.h

- exercises/practice/gigasecond/CMakeLists.txt
- exercises/practice/meetup/CMakeLists.txt
This PR is following up on [cpp: gigasecond does not compile](https://github.com/exercism/cpp-test-runner/issues/37) and [a fix for cpp-test-runner](https://github.com/exercism/cpp-test-runner/pull/38) which updated the test runner dockerfile to add a missing `boost::date_time` lib used in "gigasecond" and "meetup" CPP exercises.
[PR 38](https://github.com/exercism/cpp-test-runner/pull/38) did the following:
- install boost in test runner docker container
- add minimal tests for the test runner ensuring the library can be used by the runner
Unfortunately, this didn't fix the problem completely because the existing two exercises that use `boost::date_time`  require the static versions of boost in their `CMakeLists.txt` files.
Also related is #491.
This pull request updates those two …
> Fix compile error for exercises using boost:date_time lib

- README.md
As mentioned in #503 the Link to the Contribution Guide does not work anymore. As i was unable to find the file the Link was pointing to, i just let it point to the `docs/building/github` folder inside the `Exercism/docs` repository
> Updated Link to general contribution guides #503

- exercises/practice/gigasecond/gigasecond_test.cpp
- exercises/practice/meetup/meetup_test.cpp
Updates the documentation links in the boost test files to point to the most recent version of boost.
The real goal of this is to touch the test files so that the problems are updated for users on the website, so that this will fix the problem of building Boost in the Web UI for people who started the exercise before #495. Once merged, students in the bad state should have their exercises updated mostly automatically in the Web editor.
See https://github.com/exercism/exercism/issues/6332 for the reasoning
Closes #491
Closes #500 
Closes #514
> Update Boost documentation links.

- .appends/.github/labels.yml
We need to be able to keep a PR open, but it
has a long-term dependency.
An on-hold label would let us mark the state so we don't
keep looking at it to see why it's not merged yet.
> Add label for on-hold

- exercises/practice/collatz-conjecture/collatz_conjecture_test.cpp
This patch is a trivial fix that removes unnecessary white spaces in the source file for the test cases.
> collatz-conjecture: Remove unnecessary white spaces

- exercises/practice/collatz-conjecture/.docs/instructions.md
- exercises/practice/collatz-conjecture/.meta/config.json
- exercises/practice/collatz-conjecture/.meta/tests.toml
- exercises/practice/collatz-conjecture/collatz_conjecture_test.cpp
The first commit does a wee bit of cleanup to minimize noise in the second commit, which brings the collatz-conjecture exercise up-to-date with the problem-specifications.
> Sync collatz-conjecture with problem-specifications

- exercises/practice/nucleotide-count/.docs/instructions.md
- exercises/practice/nucleotide-count/.meta/config.json
- exercises/practice/nucleotide-count/.meta/example.cpp
- exercises/practice/nucleotide-count/.meta/tests.toml
- exercises/practice/nucleotide-count/nucleotide_count_test.cpp
This brings the nucleotide-counts exercise up to date with problem-specifications.
For clarity, it makes the change in several commits:
1. Delete entries from `tests.toml` that are not reflected in the test suite (per #370)
2. Delete tests from the nucleotide-count test suite that do not have equivalents in the `canonical-data.json`
3. Reorder nucleotide-count tests to reflect the order in `canonical-data.json`
4. Run `configlet fmt` on nucleotide-count to normalize the `config.json`
5. Normalize nucleotide-count tests to use the inputs and test descriptions from the canonical data.
6. Run `configlet sync` for the exercise and implementing the missing test.
Closes #544
Closes #539
> Sync nucleotide-count with problem-specifications

- exercises/practice/acronym/.docs/instructions.md
- exercises/practice/acronym/.meta/config.json
- exercises/practice/acronym/.meta/example.cpp
- exercises/practice/acronym/.meta/tests.toml
- exercises/practice/acronym/acronym_test.cpp
This brings the acronym exercise up to date with problem-specifications.
For clarity, it does this in several steps.
1. Rectify tests.toml, removing unimplemented tests.
2. Delete extraneous tests that don't exist upstream.
3. Normalize the test descriptions to match the canonical data.
4. Finally, sync with the upstream specification.
> Sync acronym with problem-specifications

- exercises/practice/roman-numerals/.docs/instructions.md
- exercises/practice/roman-numerals/.meta/config.json
- exercises/practice/roman-numerals/.meta/tests.toml
- exercises/practice/roman-numerals/roman_numerals_test.cpp
This brings the `roman-numerals` exercise up to date with the specification in problem-specifications.
For clarity, it does this in several steps.
1. Rectify tests.toml, removing unimplemented tests.
2. Normalize the test descriptions to match the canonical data.
3. Finally, sync with the upstream specification.
> Sync roman-numerals with problem-specifications

- exercises/practice/raindrops/.docs/instructions.md
- exercises/practice/raindrops/.meta/config.json
- exercises/practice/raindrops/.meta/tests.toml
- exercises/practice/raindrops/raindrops_test.cpp
This brings the raindrops exercise up to date with problem-specifications.
For clarity, it does this in several steps.
1. Rectify tests.toml, removing unimplemented tests.
2. Delete an extraneous test that doesn't exist upstream.
3. Normalize the test descriptions to match the canonical data.
4. Finally, sync with the upstream specification.
This PR supersedes #542, which suggests a manual change to the `instructions.md` file.
Closes #542
> Sync raindrops with problem-specifications

- exercises/practice/series/.docs/instructions.md
- exercises/practice/series/.meta/config.json
- exercises/practice/series/.meta/example.cpp
- exercises/practice/series/.meta/example.h
- exercises/practice/series/.meta/tests.toml
- exercises/practice/series/series_test.cpp
I didn't break this into individual steps, because none
of the implemented tests were reflected in the tests.toml.
For this I did a `bin/configlet sync` for the exercise, and then
recreated the test suite.
The canonical specification gives the return values as an array of strings (in JSON), so I changed the expected return type of `slice` to `vector<string>` instead of `vector<vector<int>>`.
I haven't yet changed the example solution to pass the tests; once I've got it passing I'll update the PR to be ready for review.
Closes #536
> Sync series with problem-specifications

- exercises/practice/queen-attack/queen_attack_test.cpp
Before PR #554 this exercise has a test that required the constructor to throw an exception if the positions of the two queens were identical. This PR recovers the test.
> queen-attack: Re-add test for distinct positions

- exercises/practice/nucleotide-count/.meta/example.cpp
- exercises/practice/nucleotide-count/.meta/example.h
- exercises/practice/nucleotide-count/nucleotide_count_test.cpp
Before PR #550 the constructor was required to validate the input, the member function `count(char)` had to return the count for a specific nucleotide, the member function `nucleotide_counts()` had to return a `std::map` with all four counts.
But PR #550 has changed that significantly. After syncing the tests with the canonical data there's no call to `count(char)` anymore, so each test looks like a two-step function call:
```
const nucleotide_count::counter dna("G");
const auto actual = dna.nucleotide_counts();
```
I'd call that unnecessarily complicated and unidiomatic, there's no longer a good reason to require a `class`. Let's turn the class `counter` into a function:
```
const auto actual = nucleotide_count::count("G");
```
> nucleotide-count: convert the class to a function

- .github/workflows/ci.yml
> CI: .github#L1
> The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
Ubuntu 18.04 will be phased out in GitHub actions. We should not wait too long to change along. That would also free the track from using clang 6 with C++14 to clang 10 with C++17.
> Update min required Ubuntu version to 20.04

- exercises/practice/largest-series-product/.docs/instructions.md
- exercises/practice/largest-series-product/.docs/introduction.md
- exercises/practice/largest-series-product/.meta/tests.toml
- exercises/practice/largest-series-product/largest_series_product_test.cpp
The largest-series-product exercise has been overhauled as part of a project to make practice exercises more consistent and friendly.
For more context, please see the discussion in the forum, as well as the pull request that updated the exercise in the problem-specifications repository:
- https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943
- https://github.com/exercism/problem-specifications/pull/2246 
Note that we have deprecated and removed two test cases that deal with the multiplicative identity (also referred to as an empty product). By doing this we were able to avoid talking about this at all, which makes this exercise much more approachable.
----
If you approve this pull request, I will eventually merge it. However, if …
> Sync largest-series-product docs with problem-specifications

- exercises/concept/lasagna/CMakeLists.txt
This first exercise should be as simple as possible, so we're not using a `.h` file but including the `.cpp` file directly in the the tests. This requires a minor deviation from the `CMakeLists.txt` of the other exercises.
> lasagna: Fix CMakeLists.txt

- exercises/concept/lasagna/CMakeLists.txt
Ignores compiler warnings for unused variables to let students reach the test screen, even when they have not yet implemented everything.
> Basics Concept: Ignore unused parameters during compilation

- concepts/namespaces/.meta/config.json
- concepts/namespaces/about.md
- concepts/namespaces/introduction.md
- concepts/namespaces/links.json
- config.json
This is the first smaller package to deliver the same content as the previous "Code Organization" concept.
The wording is almost the same as the previous pr #598 
There will be some more for headers, includes, and forward declarations, but namespaces are pretty independent.
>  Concept docs for "Namespaces" (closes #605)

- concepts/numbers/.meta/config.json
- concepts/numbers/about.md
- concepts/numbers/introduction.md
- concepts/numbers/links.json
- config.json
See https://github.com/exercism/cpp/issues/600
> Concept docs for "Numbers" (closes #600) 

- config.json
Log-Levels should teach includes and strings while having namespaces as a prerequisite.
> [Fix] String/Include Concept exercise order

- exercises/concept/interest-is-interesting/.docs/hints.md
Addresses #642 
Weirdly, it looks as if reflinks need to be formatted like:
`[<linkname>]: <url>` and not `[<linkname>] : <url>`
That extra space before the colon apparently does something icky.
> [interest-is-interesting]: Correct Link Formatting in `hints.md` File

- config.json
Users who chose to do learning mode can see the featured exercises in the tree.
I did all five exercises with the minimum of tools available and came to the sorting seen in the config.json file.
This is what I came up with:
---
- loops
- strings
- classes
- std::unordered_set
- string
- const
- reference
- unsigned
- string
- const
- reference
- loops
- Classes
- vector
- size_t
- iterators
- loops
- includes
---
Some of these concepts are not yet in the tree, so I will make another PR to add to their instructions about what challenges may lay ahead of the students.
> Sort featured July #12in23 exercises into the tree

- exercises/practice/allergies/.docs/instructions.append.md
- exercises/practice/high-scores/.docs/instructions.append.md
Two exercises cover topics / concept, that are not (yet) in the syllabus, so I gave them a bit more implementation hints in the `instructions.append.md`
> [Improvement] Add information for featured exercises

- exercises/practice/acronym/.docs/instructions.md
- exercises/practice/anagram/.docs/instructions.md
- exercises/practice/armstrong-numbers/.docs/instructions.md
- exercises/practice/atbash-cipher/.docs/instructions.md
- exercises/practice/binary/.docs/instructions.md
- exercises/practice/bob/.docs/instructions.md
- exercises/practice/bob/.docs/introduction.md
- exercises/practice/difference-of-squares/.docs/instructions.md
- exercises/practice/queen-attack/.docs/instructions.md
- exercises/practice/simple-linked-list/.docs/instructions.append.md
- exercises/practice/triangle/.docs/instructions.md
Went through the practice exercises to check general Markdown formatting, links, and anything else that jumped out.
Changes below:
If any of these look hanky, happy to back them out.  😄
> [Practice Exercise Lint]: General Markdown Cleanup, Link Checks, Spelling,  & Docs Sync.

- exercises/concept/interest-is-interesting/interest_is_interesting_test.cpp
Change tests to account for some rounding errors.
The way the testing is done currently pretty much only accepts the order of the exemplar solution and that should not hinder students from passing.
> [Fix] Concept - Loops: floating point testing

- exercises/concept/lasagna/.docs/introduction.md
- exercises/concept/lasagna/lasagna.cpp
Two small typos:
- the name of the function remainingOvenTime starts with an uppercase R in the comment
- the heading for the section "Whitespace" has a different level (`####`) than the headings of the other sections (`###`)
> lasagna: fix two typos

- docs/TESTS.md
Added instructions to help MacOS users that may receive errors when trying to build the tests.
> Update instructions for MacOS

- exercises/concept/troll-the-trolls/.docs/introduction.md
Current tests for choose_vehicle allow a simplistic implementation of
return option1 + " is clearly the better choice.";
to pass all tests without comparing option1 and option2.
This is due to the current tests all passing in option1 and option2 sorted in lexicographic order already.
This change swaps option1 and option2 for a couple of the tests which forces the implementation to compare the parameters.
This change will not impact existing solutions that are correctly implemented.
> Strengthen tests in Vehicle Purchase exercise

- concepts/functions/.meta/config.json
- concepts/functions/about.md
- concepts/functions/introduction.md
- concepts/functions/links.json
- config.json
This concept is called functions, although the students are using functions from the first concept exercise.
I hope it is a good place, for them, as they introduce quite a lot of noise, that is needed for later concepts, but would not help in the early stages of the tree.
I would place these in the syllabus after references to make it clear, that a reference is also a change in the function type signature.
As an exercise, I am thinking to implement an advanced version of the lasagna cooking class from the first concept. This time it will be some bigger operation with recipes that cannot be changed and stuff that plays with overloads and defaults.
Closes #660.
> [Concept] Docs -  Functions

- exercises/practice/complex-numbers/complex_numbers_test.cpp
- exercises/practice/space-age/space_age_test.cpp
Catch2 has been updated to v3 in the test-runner.
The old approximation to compare floating point numbers is outdated. This PR commit fixes the issue.
Although test files have been touched, the old solutions should no be re-run!
Thanks to @siebenschlaefer  for reporting the issue!
> fix: change test to work with Catch2 v2 and v3

- exercises/concept/ellens-alien-game/ellens_alien_game_test.cpp
- exercises/concept/freelancer-rates/freelancer_rates_test.cpp
- exercises/concept/interest-is-interesting/interest_is_interesting_test.cpp
- exercises/concept/lasagna/lasagna_test.cpp
- exercises/concept/last-will/last_will_test.cpp
- exercises/concept/log-levels/log_levels_test.cpp
- exercises/concept/pacman-rules/pacman_rules_test.cpp
- exercises/concept/vehicle-purchase/vehicle_purchase_test.cpp
- exercises/practice/complex-numbers/complex_numbers_test.cpp
- exercises/practice/high-scores/high_scores_test.cpp
This PR adds the necessary task_id information to every concept exercise test file.
This will just change the parsing of the test file and show the tests grouped by task.
It will not change the tests themselves. It is thus not needed to redo the tests.
The commit will need the `[no important files changed]` in the body.
The forum's discussion will give more information if anyone is interested:
https://forum.exercism.org/t/maintainers-new-no-important-files-changed-flag-added/6500
> feature(test-runner): add task_id for all concept ex

- exercises/practice/circular-buffer/circular_buffer_test.cpp
All exercises have been tested via the docker image to check compatibility with the new Catch2 v3. In the end, it was only the circular-buffer exercise that still caused problems.
The includes were not in the standard form and caused a problem. Existing solutions do not need retesting, the change only affects the test-runner automation.
Closes #704
> fix(test): correct includes to work with v3 runner

- exercises/concept/ellens-alien-game/.docs/introduction.md
This is a non-issue typo. Located in the CPP module docs, Introductory.md.
> Fixed incorrect type declaration.

- exercises/concept/election-day/.meta/exemplar.cpp
- exercises/concept/election-day/election_day_test.cpp
Currently many solutions modify not only the result of the winner but also other results in the process.  
This fix prevents those changes by adding another test.
> election-day/task_4: prevent collateral changes

- exercises/shared/.docs/tests.md
Added example about where to find the line to move past the next test.
> Update tests.md with example

- concepts/basics/about.md
- concepts/basics/introduction.md
- exercises/concept/lasagna/.docs/introduction.md
- exercises/practice/binary-search/.approaches/while-with-if-statements/content.md
- exercises/practice/gigasecond/.docs/introduction.md
- exercises/practice/pangram/.docs/introduction.md
In line with Exercism's spec, we're ensuring that all admonition fences are demarcated with four tildes (`~~~~`) across all repositories. We will be following up with an org-wide script that can be used to keep this consistent. [Problem Specifications](https://github.com/exercism/problem-specifications) has already been updated.
We'll automatically merge this a week from now, but feel free to merge beforehand!
- Spec: https://exercism.org/docs/building/markdown/markdown#h-special-blocks-sometimes-called-admonitions
- Meta issue: https://github.com/exercism/exercism/issues/6705
> Convert backtick (`) admonition fences to tildes (~)

- config.json
- exercises/practice/pop-count/.docs/instructions.md
- exercises/practice/pop-count/.docs/introduction.md
- exercises/practice/pop-count/.meta/config.json
- exercises/practice/pop-count/.meta/example.cpp
- exercises/practice/pop-count/.meta/example.h
- exercises/practice/pop-count/.meta/tests.toml
- exercises/practice/pop-count/CMakeLists.txt
- exercises/practice/pop-count/pop_count.cpp
- exercises/practice/pop-count/pop_count.h
- exercises/practice/pop-count/pop_count_test.cpp
- exercises/practice/pop-count/test/catch.hpp
- exercises/practice/pop-count/test/tests-main.cpp
C++ implementation for the pop-count exercise.
See https://forum.exercism.org/t/new-exercise-suggestion-pop-count/7632 for details.
> feat: add pop-count practice exercise

- concepts/headers/about.md
- concepts/headers/introduction.md
- concepts/headers/links.json
I have a good use case and idea to bring the header exercise into the track. I want to place the concept after classes because they might add a lot of questions if they stay unaddressed. The concept would need some updates to help the students along.
> feat: add class info for headers concept

- concepts/headers/about.md
- concepts/headers/introduction.md
Reduces the "advice" character of the class section and gives two examples instead.
> docs: improve wording for header concept

- exercises/practice/high-scores/.meta/example.h
- exercises/practice/high-scores/high_scores.h
> high_scores.h: #include <array>

- .github/workflows/ci.yml
- .github/workflows/format-code.yml
- .github/workflows/hello-world.yml
- .github/workflows/verify-code-formatting.yml
This PR updates GitHub Actions runners to a specific version.
This ensures that the workflow will always run on the same runner, which makes your build _stable_.
The PR updates the *-latest version with the current version, as specified in https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources.
See https://exercism.org/docs/building/github/gha-best-practices#h-pin-test-runners-to-version for more information.
> CI: pin GitHub Actions runners

- .github/workflows/ci.yml
- .github/workflows/hello-world.yml
- .github/workflows/verify-code-formatting.yml
This PR updates GitHub Actions workflows to a specific version.
This ensures that the workflow will always run the same code, which makes your build _stable_.
It will also prevent a potential security issue where a tag could be replaced by a malicious commit without consumers being aware of it.
The PR updates each non-SHA based workflow reference with the SHA of the referenced version/tag, so the current behavior should not change.
See https://exercism.org/docs/building/github/gha-best-practices#h-pin-actions-to-shas for more information.
> CI: pin GitHub Actions workflows

- exercises/concept/doctor-data/.docs/hints.md
- exercises/concept/election-day/.docs/instructions.md
- exercises/concept/election-day/.docs/introduction.md
- exercises/concept/lasagna/.docs/introduction.md
- exercises/concept/vehicle-purchase/.docs/introduction.md
As discussed [here](http://forum.exercism.org/t/detect-and-fix-typos-with-codespell/8849/6), I fix several typos in docs in this PR.
@vaeng Hope you don't mind that I tagged you in this PR, as you replied in the forum. Some unfixed typos are listed below, please let me know if any is worth fixing.
<details>
<summary>Unfixed typos</summary>
```
./concepts/vector-arrays/introduction.md:40: speficic ==> specific
./concepts/vector-arrays/about.md:40: speficic ==> specific
./concepts/classes/introduction.md:28: Wizzard ==> Wizard
./concepts/classes/about.md:29: Wizzard ==> Wizard
./concepts/references/introduction.md:33: unitialized ==> uninitialized
./concepts/references/introduction.md:47: stil ==> still
./concepts/references/about.md:33: unitialized ==> uninitialized …
```
> fix some typos in docs

- exercises/practice/leap/.articles/config.json
- exercises/practice/leap/.articles/performance/.gitignore
- exercises/practice/leap/.articles/performance/benchmark/leap_benchmark.cpp
- exercises/practice/leap/.articles/performance/content.md
- exercises/practice/leap/.articles/performance/snippet.md
~~To make the links work, this should  be merged after #759~~ :heavy_check_mark:  
~~To make the image work, https://github.com/exercism/images/pull/24 should be merged beforehand~~. :heavy_check_mark:
> feat(leap): add performance article

- config.json
- exercises/practice/two-bucket/.docs/instructions.md
- exercises/practice/two-bucket/.meta/config.json
- exercises/practice/two-bucket/.meta/example.cpp
- exercises/practice/two-bucket/.meta/example.h
- exercises/practice/two-bucket/.meta/tests.toml
- exercises/practice/two-bucket/CMakeLists.txt
- exercises/practice/two-bucket/test/catch.hpp
- exercises/practice/two-bucket/test/tests-main.cpp
- exercises/practice/two-bucket/two_bucket.cpp
- exercises/practice/two-bucket/two_bucket.h
- exercises/practice/two-bucket/two_bucket_test.cpp
This is a translation of the "two-bucket" exercise.
I've decided to provide the complete `.h` file with a definition of the `enum`, the `struct` that holds the result, and a declaration of the function.
Although I like the idea of letting the students write their own `.h` file by extracting the interface from the tests I think in this case it would be just chore.
But feel free to object, that's not a strong preference of mine.
The thing that bothered me the most is how to handle cases that are not possible to solve.
Requiring exceptions for "expected" error cases that might occur frequently and are part of the normal control flow is IMHO bad style.
If I could I would use C++23's `std::expected` but that's not an option at the moment.
Here are some alternatives:
- I could add a member …
> Add exercise two-bucket.

- exercises/practice/hamming/.meta/tests.toml
- exercises/practice/hamming/hamming_test.cpp
As discussed in #784, I was also confused about the `include = false` lines. The way I understand it, in `canonical-data.json` test cases are updated by adding a new version and a `reimplements` field that references the old version in the file. The old version is left untouched. I can imagine this is done to better be able to follow the edit history. But this also means that obsolete tests should _not_ be part of the implementation. So that is what I have done here.
> Sync hamming tests to problem-description data (#775)

- exercises/practice/sieve/.approaches/introduction.md
```
for(int idx = number * number; idx <= limit; idx +=number)
composite[idx] = true;
```
This code can be integer overflow if the limit > sqrt(maxInt). 
--> Then it leads to wrongly admit that idx <= limit. 
--> Then it leads to an out of bounds access at `composite[idx] = true` then it leads to **Segmentation Fault** (for example, when you set limit = 47000).
> `int idx` --> `size_t idx` to prevent integer overflow

- exercises/practice/armstrong-numbers/.meta/tests.toml
There are two new test cases that use big integers. They are not appropriate for standard C++, so they are not included.
> Sync `armstrong-numbers`

- exercises/practice/dnd-character/.meta/example.cpp
- exercises/practice/dnd-character/.meta/tests.toml
- exercises/practice/dnd-character/dnd_character_test.cpp
Thanks for the hints, it is now easier to understand for students.
You are correct about the last test, I removed it.
> fix: improve tests and example for dnd character exercise

- exercises/practice/dnd-character/dnd_character_test.cpp
Thanks to @siebenschlaefer for finding that fix and [oxe-b](https://forum.exercism.org/t/possible-bug-in-dnd-character/9957) for reporting.
> fix: make matcher for catch2 v2 and v3 compatible

- exercises/practice/perfect-numbers/.meta/example.h
- exercises/practice/perfect-numbers/.meta/tests.toml
- exercises/practice/perfect-numbers/perfect_numbers_test.cpp
I also added better display of enums in the rest runner and changed the enum to an enum class.
I hope that small fix is fine and will not produce any hickups.
> tests: update perfect numbers exercise

- exercises/concept/troll-the-trolls/.docs/instructions.md
- exercises/concept/troll-the-trolls/troll_the_trolls_test.cpp
- modified the instructions, hopefully they are now easier to understand.
- moved the test "Troll posts are visible to non-trolls" up and fixed its title.
- added a new test "Non-troll posts are visible to trolls"
fixes #792
> Improve troll-the-trolls, task 2

- exercises/practice/parallel-letter-frequency/.docs/instructions.append.md
- exercises/practice/parallel-letter-frequency/.meta/example.cpp
- exercises/practice/parallel-letter-frequency/parallel_letter_frequency.cpp
- exercises/practice/parallel-letter-frequency/parallel_letter_frequency_test.cpp
Also fix the "thread pool" link in `instructions.append.md`.
> fix: missing assertions in parallel-letter-frequency test

- config.json
- exercises/concept/lasagna-master/.docs/hints.md
- exercises/concept/lasagna-master/.docs/instructions.md
- exercises/concept/lasagna-master/.docs/introduction.md
- exercises/concept/lasagna-master/.docs/introduction.md.tpl
- exercises/concept/lasagna-master/.meta/config.json
- exercises/concept/lasagna-master/.meta/design.md
- exercises/concept/lasagna-master/.meta/exemplar.cpp
- exercises/concept/lasagna-master/.meta/exemplar.h
- exercises/concept/lasagna-master/lasagna_master.cpp
- exercises/concept/lasagna-master/lasagna_master.h
- exercises/concept/lasagna-master/lasagna_master_test.cpp
That has slipped, sorry.
I finished the concept but never made the respective exercise.
> feat: add functions exercise

- exercises/practice/bank-account/.meta/tests.toml
- exercises/practice/bank-account/bank_account_test.cpp
Update the Tests according to the How-to. If i miss something then please let me know.
> Fixed bank-account tests

- concepts/auto/.meta/config.json
- concepts/auto/about.md
- concepts/auto/introduction.md
- concepts/auto/links.json
- config.json
As we will soon have a smart pointer concept, it makes sense to introduce auto as well.
> feat: add auto concept

- exercises/practice/crypto-square/.meta/config.json
- exercises/practice/crypto-square/.meta/tests.toml
- exercises/practice/crypto-square/crypto_square_test.cpp
The original tests expected that the implementation also exposes intermediate steps, such as the normalized plaintext. I think this unnecessarily restricts the implementation and is also not reflected in the canonical data. So now I changed all tests to exactly correspond to the canonical data. Let me know if that's not what I should have done. I can also just add the one extra test case. But adding the test UUIDs would be a bit hard then ...
> tests: update crypto-square exercise

- concepts/smart-pointers/.meta/config.json
- concepts/smart-pointers/about.md
- concepts/smart-pointers/introduction.md
- concepts/smart-pointers/links.json
- config.json
This is long, but I think it is pretty straightforward. Maybe I have tunnel vision and this is not readable at all :D
> feat: add smart pointer concept

- bin/check-formatting.sh
The `bin/check-formatting.sh` script changed its directory to `bin` as the first step, consequently expecting paths of files to check to be relative to `bin`, when typically they would be given relative to the working directory. When not finding a file, the script would just print a warning, but still exit with error code 0, which is probably the reason why this went unnoticed for quite a while.
This commit fixes the relative directory issue. Further, when a given path cannot be checked, we return a non-zero code now. Lastly, the script would count the number of files with formatting issues and return that number as error code. This has the issue that if the number of violating files is a multiple of 256, error code would falsly be returned.
> fix(check-formatting.sh): use relative directory

- exercises/concept/troll-the-trolls/troll_the_trolls_test.cpp
Corrected the word 'guest' in the last test that should have been 'user' and 'mod'
> Minor typo fix

- exercises/concept/lasagna-master/.docs/instructions.md
The aim of this PR is to try to clarify the instructions of Task 3.
> docs: fix instructions of lasagna master

- concepts/functions/about.md
Small typo where length was spelled lenghth instead of length.
> Update about.md small typo

- concepts/loops/introduction.md
`i` is the counter of the `for loop` that will be used to get the module of `2`, instead of `n`.
> docs: n is unknown variable

- exercises/concept/interest-is-interesting/.docs/introduction.md
Fixing this also on the documentation of the exercise, This should be pointing to `i`.
Previous PR was fixing it on the learning section but it seems it is also on the exercise itself
> docs: N is not existing variable

- exercises/practice/prime-factors/.meta/config.json
- exercises/practice/prime-factors/.meta/example.cpp
- exercises/practice/prime-factors/.meta/example.h
- exercises/practice/prime-factors/.meta/tests.toml
- exercises/practice/prime-factors/prime_factors_test.cpp
- Updated all the test cases including new ones added
- Regenerated test.toml with configlet
- Configlet test says all filepaths, metadata, and tests for prime-factors are up to date
> UPDATE test cases from problem specifications for prime-factors

- exercises/concept/ellens-alien-game/ellens_alien_game_test.cpp
There is a requirement for exercise ellens-alien-game's hit() method which states: "Make sure that the health points do not drop below zero." Adding a "get_health() == 0" at the end of the hit test now tests whether this is the case.
> Hit requirement untested

- concepts/literals/about.md
- concepts/literals/introduction.md
Special blocks (admonissions) are renedered by themselves without including the rest of the page. A reference link from the bottom of the file is therefore not available and cannot be resolved properly. This is fixed by moving it to the bottom of the block instead of the bottom of the file.
> fix(literals): move reference link into admonition

- exercises/practice/reverse-string/.approaches/using-the-standard-lib/content.md
Fixing a minor typo and punctuation error in the "Using the standard library" approach to `reverse-string`.
> docs: minor typo fix in reverse-string approach

- concepts/pointers/.meta/config.json
- concepts/pointers/about.md
- concepts/pointers/introduction.md
- concepts/pointers/links.json
- config.json
I would put that concept after "references" and follow up with smart pointers. the trinity of confusion.
I think [windowing system](https://github.com/exercism/javascript/blob/main/exercises/concept/windowing-system/.docs/instructions.md) might be a fitting concept exercise.
> feat: add pointers concept

- exercises/practice/say/.meta/tests.toml
- exercises/practice/say/say_test.cpp
This PR is the result of running this command:
using the [test creation helper tool](https://github.com/exercism/cpp/wiki/Test-Cases-for-Practice-Exercises#test-creation-helper-tool) linked in the wiki, with some modifications to the code necessary for the tool to work.
> tests: update say exercise

- exercises/practice/triangle/.meta/tests.toml
- exercises/practice/triangle/triangle_test.cpp
Hello,
I followed the guide to synch and update the tests for the triangle exercise. I am not sure if there is another part to this process. If yes, please advise.
Thank you kindly!
> update triangle tests

- exercises/practice/say/say_test.cpp
I think a student could be very confused by this comment when we expect them to throw in case of an error. This comment is verbatim copy from the [problem specification](https://github.com/exercism/problem-specifications/blob/main/exercises/say/canonical-data.json#L4). At the very least, it should be reworded to make clear that we expect an exception, but I think it's best removed.
> fix(say): remove misleading comment

- exercises/practice/roman-numerals/.meta/example.cpp
- exercises/practice/roman-numerals/.meta/example.h
- exercises/practice/roman-numerals/.meta/tests.toml
- exercises/practice/roman-numerals/roman_numerals.cpp
- exercises/practice/roman-numerals/roman_numerals.h
- exercises/practice/roman-numerals/roman_numerals_test.cpp
I added the test for 3888. In the process of doing that, it appears the test order in tests.toml has since changed so I updated the the test suite order to reflect that
> Sync and sort roman-numeral tests

- concepts/numbers/about.md
- concepts/numbers/introduction.md
- exercises/concept/freelancer-rates/.docs/introduction.md
Fix typo: 'These operators modifies' -> 'These operators modify'.
> Fix typo: 'These operators modifies' -> 'These operators modify'.

- concepts/literals/introduction.md
> docs: update literals introduction with C++23 standard information

- docs/INSTALLATION.md
@vaeng I took a first stab at writing the installation instructions for Boost on Windows. Could you take a look?
> Install boost on windows

- docs/TESTS.md
This PR updates the documentation to improve the "MacOS with Make when using the Exercism CLI" section. The updated instructions clarify the process of configuring, testing, and submitting C++ exercises with the Exercism CLI on MacOS.
This update aligns the section with existing style and cadence in the documentation while providing additional clarity for users who may be unfamiliar with the nuances of the Exercism CLI setup. It aims to minimize confusion and ensure a smooth setup process on MacOS.
- Enhances the clarity of instructions for MacOS users.
- Provides explicit details to streamline the C++ exercise workflow with the Exercism CLI.
- Verified the commands and workflow on MacOS using `Unix Makefiles` with the Exercism CLI.
- Ensured documentation style and tone are consistent …
> Update Documentation: Add MacOS with Make instructions for Exercism CLI

- exercises/concept/freelancer-rates/freelancer_rates_test.cpp
> test: make freelancer rates more robust

- exercises/concept/lasagna-master/lasagna_master_test.cpp
- exercises/concept/pacman-rules/pacman_rules_test.cpp
- exercises/practice/allergies/allergies_test.cpp
- exercises/practice/complex-numbers/complex_numbers_test.cpp
- exercises/practice/linked-list/linked_list_test.cpp
- exercises/practice/luhn/luhn_test.cpp
- exercises/practice/queen-attack/queen_attack_test.cpp
- exercises/practice/raindrops/raindrops_test.cpp
- exercises/practice/two-bucket/two_bucket_test.cpp
> fix: have test name on one line again

- exercises/concept/freelancer-rates/.docs/introduction.md
Just fixing a minimal typo in the introduction docs
> docs: typo '9421' -> '9241'

- exercises/concept/making-the-grade/.docs/hints.md
- exercises/concept/making-the-grade/.docs/instructions.md
While the instructions section contains only 5 steps described in the instructions.md file, 6 steps are visible on the [web](https://exercism.org/tracks/cpp/exercises/making-the-grade/edit).
Quick fix is to move 'How to calculate the intervals' to hints.md.
> Update making-the-grade instructions and hints to remove extra step.

- .github/workflows/ci.yml
Ubuntu 20.04 LTS support is going to stop this May.
Pipeline already stopped working.
> chore: update github ci tools to ubuntu 22.04

- config.json
- exercises/practice/alphametics/.docs/instructions.md
- exercises/practice/alphametics/.meta/config.json
- exercises/practice/alphametics/.meta/example.cpp
- exercises/practice/alphametics/.meta/example.h
- exercises/practice/alphametics/.meta/tests.toml
- exercises/practice/alphametics/CMakeLists.txt
- exercises/practice/alphametics/alphametics.cpp
- exercises/practice/alphametics/alphametics.h
- exercises/practice/alphametics/alphametics_test.cpp
- exercises/practice/alphametics/test/catch.hpp
- exercises/practice/alphametics/test/tests-main.cpp
Hey,
@ahans @vaeng
Sorry I had to rework my branch structure to submit multiple PRs for different exercises.
I didn't think about the PR deleting itself when I reset my main.
Here is the PR again, our last topic was:
> Added "alphametics" exercise

- config.json
- exercises/practice/flower-field/.docs/instructions.md
- exercises/practice/flower-field/.docs/introduction.md
- exercises/practice/flower-field/.meta/config.json
- exercises/practice/flower-field/.meta/example.cpp
- exercises/practice/flower-field/.meta/example.h
- exercises/practice/flower-field/.meta/tests.toml
- exercises/practice/flower-field/CMakeLists.txt
- exercises/practice/flower-field/flower_field.cpp
- exercises/practice/flower-field/flower_field.h
- exercises/practice/flower-field/flower_field_test.cpp
- exercises/practice/flower-field/test/catch.hpp
- exercises/practice/flower-field/test/tests-main.cpp
https://forum.exercism.org/t/suggestion-deprecate-minesweeper-for-flower-field/17967
> Add `flower-field`, deprecating `minesweeper`

- exercises/concept/last-will/.docs/introduction.md
> fix: small typo

- exercises/practice/complex-numbers/complex_numbers_test.cpp
in `exercises/practice/complex_numbers/complex_numbers_test.cpp`: when running the first few test cases without the use of the require_approx_equal helper function, a warning is issued which will be treated as an error
> bugfix: unused function complex_numbers_test.cpp
