sum-of-multiples/sum_of_multiples_test.cpp

Addresses https://github.com/exercism/todo/issues/51.

Add missing sum of multiples test

---

docs/RESOURCES.md

Hey there,
I've recently started the C++ track and seen there's a missing resources section in http://exercism.io/languages/cpp. I though I could make one since I know some helpful resources about C++, so here it is.
All this pull request includes is a new `RESOURCES.md` file with three resources that have helped me a lot. Hope other will find them helpful as well.

Created RESOURCES.md file

---

triangle/example.cpp
triangle/example.h
triangle/triangle_test.cpp

Fix inconsistency in triangle test

---

robot-name/robot_name_test.cpp

Addresses discussion in exercism/exercism.io#2441

Robot names begin with two alphabetic characters

---

docs/TESTS.md

[Running the Tests](http://exercism.io/languages/cpp) has a similar problem as #66 in that the first bulleted list appears inline and unformatted. Hopefully this fixes it.

Hopefully fix formatting of list in TESTS.md.

---

docs/ABOUT.md

Added ABOUT.md page in docs folder.
Went through @LegalizeAdulthood's comment in #64 and tried to follow the instruction.
Please review.

Added ABOUT.md page

---

scrabble-score/scrabble_score_test.cpp

Update scrabble word oxyphenbutazone

---

triangle/triangle_test.cpp

closes https://github.com/exercism/x-common/issues/202   
closes https://github.com/exercism/xcpp/issues/65

removed 242 case

---

docs/INSTALLATION.md

Didn't work for me without adding it. Copied from g++ installation docs further up page.

Add `apt-get update` to boost install

---

CMakeLists.txt
config.json
exercises/allergies/CMakeLists.txt
exercises/allergies/allergies_test.cpp
exercises/allergies/example.cpp
exercises/allergies/example.h

First time porting one over; let me know if I need to fix anything / if I made some style errors & I'll get them fixed.
Wasn't sure where best to put it in config.json so it's at the end.
Also, would you prefer I squashed it all to 1 patch, or leave the commits separate like this?

Port allergies exercise

---

CMakeLists.txt
config.json
exercises/bracket-push/CMakeLists.txt
exercises/bracket-push/bracket_push_test.cpp
exercises/bracket-push/example.cpp
exercises/bracket-push/example.h

I added it to the end of the list of exercises, since I wasn't sure where in the list it should go.

Pass bracket-push

---

config.json

Adds uuids and new 'default' config settings for the newly merged problems. Using this PR just to sanity check the json config.
Closes #144

Update json for new tracks.

---

CMakeLists.txt
config.json
exercises/pangram/CMakeLists.txt
exercises/pangram/example.cpp
exercises/pangram/example.h
exercises/pangram/pangram_test.cpp

Implementing pangram.

---

docs/TESTS.md

In TDD fashion I made the smallest possible change that would have prevented me from having to ask for help on chat.  Then I noticed a lot of common words and refactored it out.

Update steps to run tests.

---

docs/INSTALLATION.md

Fixed a little grammatical error on line 18: Release->Released*

Small grammatical mistake Line 18

---

config.json

I've set hello-world to auto_approve for issue #183

Added auto_approve true for hello-world

---

config.json

I've selected 10 core exercises based upon difficulties, and added unlocked_by to the rest of the exercises (apart from a couple which are neither core nor locked by default - "bonus exercises")
Issue #183

Added core and unlocked_by to exercises

---

exercises/bracket-push/README.md
exercises/crypto-square/README.md
exercises/hamming/README.md
exercises/say/README.md
exercises/series/README.md
exercises/sieve/README.md

Running `configlet generate .` has updated these READMEs

Updated READMEs from configlet generate

---

exercises/crypto-square/README.md
exercises/hamming/README.md

update the outdated READMEs using configlet

update READMEs using configlet

---

config/maintainers.json

Bio, etc to follow; let's do some real work first.

Add KevinWMatthews as maintainer

---

.travis.yml
exercises/acronym/example.cpp

* Using ninja instead of make on travis to take advantage of multicore (travis machines have 2 cores, and ninja does interleave the output unlike `make -j2` would).
* Adding a modern compiler.
* Cleaning up how the compilers are set a little bit.

Cleaning up travis settings.

---

CMakeLists.txt
config.json
exercises/pascals-triangle/CMakeLists.txt
exercises/pascals-triangle/README.md
exercises/pascals-triangle/example.cpp
exercises/pascals-triangle/example.h
exercises/pascals-triangle/pascals_triangle_test.cpp

Added a new exercise from the available problems.

Implement Exercise - Pascal's Triangle

---

exercises/difference-of-squares/CMakeLists.txt
exercises/difference-of-squares/difference_of_squares_test.cpp
exercises/difference-of-squares/test/catch.hpp
exercises/nth-prime/CMakeLists.txt
exercises/nth-prime/nth_prime_test.cpp
exercises/nth-prime/test/catch.hpp
exercises/queen-attack/CMakeLists.txt
exercises/queen-attack/queen_attack_test.cpp
exercises/queen-attack/test/catch.hpp
exercises/say/CMakeLists.txt
exercises/say/say_test.cpp
exercises/say/test/catch.hpp
exercises/sieve/CMakeLists.txt
exercises/sieve/sieve_test.cpp
exercises/sieve/test/catch.hpp

All very straightforward conversion to Catch. Will merge these myself on April 13th unless something comes up.
Related to #253.

Boost -> Catch: Everything unlocked by leap.

---

exercises/allergies/CMakeLists.txt
exercises/allergies/allergies_test.cpp
exercises/allergies/test/catch.hpp
exercises/prime-factors/CMakeLists.txt
exercises/prime-factors/prime_factors_test.cpp
exercises/prime-factors/test/catch.hpp
exercises/robot-name/CMakeLists.txt
exercises/robot-name/robot_name_test.cpp
exercises/robot-name/test/catch.hpp
exercises/sum-of-multiples/CMakeLists.txt
exercises/sum-of-multiples/sum_of_multiples_test.cpp
exercises/sum-of-multiples/test/catch.hpp

*Except for gigasecond, which needs more care.
Robot-name has a fix for a poorly written test, but everything else was a straight simple conversion.
To be merged on April 13th unless something comes up.
Related to #253

Boost -> Catch: Everything unlocked by reverse-string.

---

exercises/atbash-cipher/CMakeLists.txt
exercises/atbash-cipher/atbash_cipher_test.cpp
exercises/atbash-cipher/test/catch.hpp
exercises/beer-song/CMakeLists.txt
exercises/beer-song/beer_song_test.cpp
exercises/beer-song/test/catch.hpp
exercises/binary-search/CMakeLists.txt
exercises/binary-search/binary_search_test.cpp
exercises/binary-search/test/catch.hpp
exercises/clock/CMakeLists.txt
exercises/clock/clock_test.cpp
exercises/clock/test/catch.hpp
exercises/trinary/CMakeLists.txt
exercises/trinary/test/catch.hpp
exercises/trinary/trinary_test.cpp

*Except meetup because of it's dependence on boost datetime.
Clock needed explicit error messages to appropriately handle it's test suite, but everything else was very standard.
Will merge on April 20th unless something comes up.
Related to #253

Boost -> Catch: Everything unlocked by space-age and triangle.

---

exercises/anagram/CMakeLists.txt
exercises/anagram/anagram_test.cpp
exercises/anagram/example.cpp
exercises/anagram/test/catch.hpp
exercises/bob/CMakeLists.txt
exercises/bob/bob_test.cpp
exercises/bob/test/catch.hpp
exercises/bracket-push/CMakeLists.txt
exercises/bracket-push/bracket_push_test.cpp
exercises/bracket-push/test/catch.hpp
exercises/crypto-square/CMakeLists.txt
exercises/crypto-square/crypto_square_test.cpp
exercises/crypto-square/example.cpp
exercises/crypto-square/test/catch.hpp
exercises/etl/CMakeLists.txt
exercises/etl/etl_test.cpp
exercises/etl/test/catch.hpp
exercises/word-count/CMakeLists.txt
exercises/word-count/test/catch.hpp
exercises/word-count/word_count_test.cpp

Will merge on April 20th unless something comes up. Nothing interesting here, though I did fix some formatting problems I introduced in #238.
See #253

Boost -> Catch: Everything unlocked by raindrops and pangram.

---

exercises/binary-search-tree/example.h

Insert can also benefit from the perfect forwarding.
Also, I cleaned up the code a little.
I guess the example doesn't need to be perfect, but I will want to use it for the mentoring notes.

use perferct forwarding also for insert

---

exercises/anagram/anagram_test.cpp

Update anagram exercise test cases

---

docs/TESTS.md

changed "impementation" on line 33 to "implementation"

Update Test.md with spelling change

---

config.json
exercises/two-fer/CMakeLists.txt
exercises/two-fer/README.md
exercises/two-fer/example.h
exercises/two-fer/test/catch.hpp
exercises/two-fer/test/tests-main.cpp
exercises/two-fer/two_fer.cpp
exercises/two-fer/two_fer.h
exercises/two-fer/two_fer_test.cpp

two-fer is one of the simplest exercises. It's part of the core
exercises in many language tracks (e.g. JavaScript, Java, Python, Ruby)
and AFAIK it was the first exercise that got automated mentoring (in
the Ruby track).
It's simple, but IMHO it's interesting because AFAIK it'd be the only
C++ exercise where the model solution uses an argument with a default
value.

Implement the exercise "two-fer"

---

README.md
config.json

Are there other topics that need changes?
fix #329

fix inconsistency in exercise topics

---

config/maintainers.json

As per the slack instructions.

maintainers: Add Rohit Goswami

---

config/maintainers.json

As per instructions from Slack.

Added silvanocerza to maintainers

---

.github/workflows/ci.yml

Removes/Adds workarounds for Boost running on Github Actions.

Fix Boost issues in Github Actions

---

.clang-format
.github/workflows/format-code.yml
.github/workflows/verify-code-formatting.yml
check-formatting.sh

This should solve #274.
I've not formatted any code in this PR just implemented a way to enforce it, I was thinking of creating a separate PR after this one is merged with a single commit that formats all C++ code.

Implemented enforcement of code formatting style

---

concepts/strings/.meta/config.json
config.json

- Fix config.json lint errors
- Add missing .meta/config.json file for strings concept

fix lint errors

---

exercises/practice/hello-world/.meta/config.json
exercises/practice/hello-world/hello_world.cpp

Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46

🤖 Simplify `hello-world` stub

---

docs/TESTS.md

Additional information about how to run code on Mac in XCode based on https://github.com/exercism/cpp/issues/479#issuecomment-915826027.

documentation update

---

config.json
exercises/practice/bank-account/.docs/instructions.md
exercises/practice/bank-account/.meta/config.json
exercises/practice/bank-account/.meta/example.cpp
exercises/practice/bank-account/.meta/example.h
exercises/practice/bank-account/CMakeLists.txt
exercises/practice/bank-account/bank_account.cpp
exercises/practice/bank-account/bank_account.h
exercises/practice/bank-account/bank_account_test.cpp
exercises/practice/bank-account/test/catch.hpp
exercises/practice/bank-account/test/tests-main.cpp

Implementation of the Bank Account Exercise. 
As always i'm happy to hear some improvements =)

Implementation of exercise Bank account

---

exercises/practice/space-age/.docs/instructions.md
exercises/practice/space-age/.meta/config.json
exercises/practice/space-age/.meta/tests.toml

This brings in changes to the instructions and metadata,
but I chose not to add the proposed additional test, as it
adds error-handling to an exercise that doesn't already have it,
and I don't think that the addition of error-handling makes
this exercise more interesting.

Sync space-age with problem-specifications

---

exercises/practice/queen-attack/.docs/instructions.md
exercises/practice/queen-attack/.meta/config.json
exercises/practice/queen-attack/.meta/example.cpp
exercises/practice/queen-attack/.meta/tests.toml
exercises/practice/queen-attack/queen_attack_test.cpp

The tests implemented in the queen-attack test suite had no overlap
with the tests listed in tests.toml.
I've therefore done a complete overhaul in one fell swoop rather than
trying to break it into step-by-step commits.
Closes #535

Sync queen-attack with problem-specifications

---

exercises/practice/sieve/.approaches/config.json
exercises/practice/sieve/.approaches/introduction.md
exercises/practice/sieve/.approaches/vector-of-bools/content.md
exercises/practice/sieve/.approaches/vector-of-bools/snippet.txt

Sieve approach

---

exercises/practice/secret-handshake/.approaches/config.json
exercises/practice/secret-handshake/.approaches/if-statements-with-reverse/content.md
exercises/practice/secret-handshake/.approaches/if-statements-with-reverse/snippet.txt
exercises/practice/secret-handshake/.approaches/introduction.md
exercises/practice/secret-handshake/.approaches/iterate-once/content.md
exercises/practice/secret-handshake/.approaches/iterate-once/snippet.txt

Approaches for Secret Handshake. Please let me now if there are any show-stoppers. Anything else is encouraged to be done after the initial merge.

Secret Handshake approaches

---

exercises/practice/pangram/.approaches/algorithm-allof/content.md
exercises/practice/pangram/.approaches/algorithm-allof/snippet.txt
exercises/practice/pangram/.approaches/bitset-all/content.md
exercises/practice/pangram/.approaches/bitset-all/snippet.txt
exercises/practice/pangram/.approaches/config.json
exercises/practice/pangram/.approaches/introduction.md

Approaches for Pangram. Please let me know if there are any show-stoppers. Anything else can be added after merge.

Pangram approaches

---

exercises/practice/simple-linked-list/.docs/instructions.append.md
exercises/practice/simple-linked-list/.meta/example.cpp
exercises/practice/simple-linked-list/.meta/example.h
exercises/practice/simple-linked-list/simple_linked_list.cpp
exercises/practice/simple-linked-list/simple_linked_list.h

Including the simple linked list for the badge left some room for improvement.

Update files according to c++ standard

---

exercises/practice/simple-linked-list/.meta/example.cpp
exercises/practice/simple-linked-list/.meta/example.h
exercises/practice/simple-linked-list/simple_linked_list.cpp
exercises/practice/simple-linked-list/simple_linked_list.h

Simple-Linked-List - improve compatibility #584

---

concepts/includes/.meta/config.json
concepts/includes/about.md
concepts/includes/introduction.md
concepts/includes/links.json
config.json

This is the second smaller package to deliver the same content as the previous "Code Organization" concept.
The wording is almost the same as the previous pr https://github.com/exercism/cpp/pull/598
In the tree, it will follow the namespace concept as the std libs use the std namespace and the namespace resolution operator.
There will be some more for headers and forward declarations.

Concept docs for "Includes" (closes #607)

---

concepts/numbers/about.md

about.md was missing text from introduction.md

[Fix] Concept docs - Numbers

---

concepts/comparisons/.meta/config.json
concepts/comparisons/about.md
concepts/comparisons/introduction.md
concepts/comparisons/links.json
config.json

Comparisons as a concept will follow booleans and strings in the syllabus tree

Concept docs for "comparisons"

---

concepts/vector-arrays/.meta/config.json
concepts/vector-arrays/about.md
concepts/vector-arrays/introduction.md
concepts/vector-arrays/links.json
config.json

The plan is to take the [swift "magician in-training"](https://github.com/exercism/swift/blob/main/exercises/concept/magician-in-training/.docs/instructions.md) exercise to go along with the docs.
This will be followed by loops to build up for-each and the iterator concepts.

[Concept] Docs - Vectors and Arrays

---

config.json
exercises/practice/perfect-numbers/.docs/instructions.md
exercises/practice/perfect-numbers/.meta/config.json
exercises/practice/perfect-numbers/.meta/example.cpp
exercises/practice/perfect-numbers/.meta/example.h
exercises/practice/perfect-numbers/.meta/tests.toml
exercises/practice/perfect-numbers/CMakeLists.txt
exercises/practice/perfect-numbers/perfect_numbers.cpp
exercises/practice/perfect-numbers/perfect_numbers.h
exercises/practice/perfect-numbers/perfect_numbers_test.cpp
exercises/practice/perfect-numbers/test/catch.hpp
exercises/practice/perfect-numbers/test/tests-main.cpp

ping @vaeng for guidance and feedback. I ran `configlet` for the docs and for `config.json` formatting, and added a UUID and other metadata to the track-level `config.json`.

WIP: perfect-numbers

---

concepts/loops/.meta/config.json
concepts/loops/about.md
concepts/loops/introduction.md
concepts/loops/links.json
config.json

Will be accompanied by the [interest-is-interesting](https://github.com/exercism/csharp/tree/main/exercises/concept/) exercise.

[Concept] Docs - Loops

---

concepts/numbers/.meta/config.json
concepts/numbers/introduction.md

commit d268fc1a751ec5ecf1c3d0eeaaccd128a6283628
Author: tesarect <karthikn.balasubramanian@gmail.com>
Date:   Sat Jun 17 13:04:12 2023 +0530
Explanation & examples has been added for assignment operator along with compound assignment operators.

Update numbers introduction - Fixed

---

config.json
exercises/concept/interest-is-interesting/.docs/hints.md
exercises/concept/interest-is-interesting/.docs/instructions.md
exercises/concept/interest-is-interesting/.docs/introduction.md
exercises/concept/interest-is-interesting/.docs/introduction.md.tpl
exercises/concept/interest-is-interesting/.meta/config.json
exercises/concept/interest-is-interesting/.meta/design.md
exercises/concept/interest-is-interesting/.meta/exemplar.cpp
exercises/concept/interest-is-interesting/CMakeLists.txt
exercises/concept/interest-is-interesting/interest_is_interesting.cpp
exercises/concept/interest-is-interesting/interest_is_interesting_test.cpp
exercises/concept/interest-is-interesting/test/catch.hpp
exercises/concept/interest-is-interesting/test/tests-main.cpp

Add the interest-is-interesting exercise to explore loops.

[Concept] Exercise - Loops

---

concepts/vector-arrays/about.md
concepts/vector-arrays/introduction.md
config.json
exercises/concept/making-the-grade/.docs/hints.md
exercises/concept/making-the-grade/.docs/instructions.md
exercises/concept/making-the-grade/.docs/introduction.md
exercises/concept/making-the-grade/.docs/introduction.md.tpl
exercises/concept/making-the-grade/.meta/config.json
exercises/concept/making-the-grade/.meta/design.md
exercises/concept/making-the-grade/.meta/exemplar.cpp
exercises/concept/making-the-grade/CMakeLists.txt
exercises/concept/making-the-grade/making_the_grade.cpp
exercises/concept/making-the-grade/making_the_grade_test.cpp
exercises/concept/making-the-grade/test/catch.hpp
exercises/concept/making-the-grade/test/tests-main.cpp

Making the grade trains loops, arrays and vectors.
It will pave the path to introduce "for loops" at a later stage

[Concept] Exercise - Vector-Arrays (with looping)

---

exercises/practice/high-scores/.docs/instructions.append.md

There wasn't anything else that stood out to me, so flagging this as a small change.

[Practice Exercise Link Sweep]: Corrected links in `High Scores`

---

concepts/classes/about.md

Start of addressing #650.  
Copied the `introduction.md` to the `about.md`. 
This probably could use another read-through and addition of perhaps some more information or places to explore/dig deeper?

[Classes Concept]: Copied Introduction to About for First Pass

---

config.json
exercises/concept/ellens-alien-game/.docs/hints.md
exercises/concept/ellens-alien-game/.docs/instructions.md
exercises/concept/ellens-alien-game/.docs/introduction.md
exercises/concept/ellens-alien-game/.docs/introduction.md.tpl
exercises/concept/ellens-alien-game/.meta/config.json
exercises/concept/ellens-alien-game/.meta/design.md
exercises/concept/ellens-alien-game/.meta/exemplar.cpp
exercises/concept/ellens-alien-game/CMakeLists.txt
exercises/concept/ellens-alien-game/ellens_alien_game.cpp
exercises/concept/ellens-alien-game/ellens_alien_game_test.cpp
exercises/concept/ellens-alien-game/test/catch.hpp
exercises/concept/ellens-alien-game/test/tests-main.cpp

This is the last piece of the puzzle, that I would insert before the tree can go public.

[Concept] Exercise - Classes

---

config.json

[Concept] Make the tree public

---

config.json

Added some of the existing exercises to the tree.
We might have to add new exercises to make it less focused on strings and loops.

[Improve] Link practice exercises to syllabus 

---

exercises/concept/last-will/last_will_test.cpp

last-will: Fix order of declaration for Clang

---

exercises/concept/last-will/.docs/instructions.md

[Improvement] Last Will - Add wording for more clarity in task 3

---

concepts/enums/.meta/config.json
concepts/enums/about.md
concepts/enums/introduction.md
concepts/enums/links.json
config.json

Will get an exercise with the switch concept in the style of https://github.com/exercism/csharp/blob/main/exercises/concept/attack-of-the-trolls/.docs/instructions.md

[Concept] Docs - Enumerations

---

concepts/strings/introduction.md
exercises/concept/log-levels/.docs/introduction.md

It should now be easier to get the same result as the code by counting the letters in the example.
Fixes #673.

[Improve] String find example

---

concepts/strings/introduction.md
exercises/concept/log-levels/.docs/introduction.md

[Improve] Make fully qualified string type name explicit

---

exercises/shared/.docs/tests.md

@vaeng noticed the URL was out of date so fixed this and added reference links.

Update Exercism URL, add reference links

---

concepts/numbers/about.md
exercises/concept/freelancer-rates/.docs/introduction.md

Updated 
- concepts/numbers/about.md and 
- exercises/concept/freelancer-rates/.docs/introduction.md 
with concepts/numbers/introduction.md

#638 Synced about.md and exercises introduction.md with new introduction.md

---

exercises/shared/.docs/tests.md

I found a stray C++11 in our docs.

Update C++ version in the tests docs.

---

exercises/concept/making-the-grade/making_the_grade.cpp

In function letter_grades, comment was about previous function, above_threshold

Update making_the_grade.cpp - fixed wrong TODO comment

---

exercises/concept/log-levels/.docs/introduction.md

Missing 'string' in code example.

fix: update introduction.md

---

exercises/concept/making-the-grade/.docs/introduction.md

The vector declaration in this introduction is obviously incorrect. I've made a small correction. Please accept. Thank you!

Correct the vector declaration

---

config.json

**Do not merge before** preparation scripts have finished. This has to be merged after the okay from Eric.
(Rep is high, because I forgot to set the label in the representer)

build: activate representer

---

concepts/vector-arrays/about.md
concepts/vector-arrays/introduction.md
exercises/concept/making-the-grade/.docs/introduction.md

Fix(making the grade): correct "witch example"

---

exercises/concept/freelancer-rates/.docs/instructions.md

docs: improve instructions for freelancer-rates

---

exercises/concept/freelancer-rates/CMakeLists.txt

feat: allow unused parameters for freelancer rates

---

concepts/classes/about.md
concepts/classes/introduction.md

fix: spelling in classes concept

---

exercises/practice/triangle/triangle_test.cpp

BREAKING CHANGE: forces students to use enums
Closes #525

feat!: improve error msg for triangle ex

---

exercises/concept/lasagna/lasagna_test.cpp

fix(lasagna): typo in test file

---

config.json
exercises/practice/rotational-cipher/.docs/instructions.md
exercises/practice/rotational-cipher/.meta/config.json
exercises/practice/rotational-cipher/.meta/example.cpp
exercises/practice/rotational-cipher/.meta/example.h
exercises/practice/rotational-cipher/.meta/tests.toml
exercises/practice/rotational-cipher/CMakeLists.txt
exercises/practice/rotational-cipher/rotational_cipher.cpp
exercises/practice/rotational-cipher/rotational_cipher.h
exercises/practice/rotational-cipher/rotational_cipher_test.cpp
exercises/practice/rotational-cipher/test/catch.hpp
exercises/practice/rotational-cipher/test/tests-main.cpp

According to https://gist.github.com/ErikSchierboom/2f121db2bc55003129408edcd19183dc, this exercise is the second most popular (among other tracks) exercise, that has not yet been made available on the cpp track.
Let's change that.

feat: add rotational cipher exercise

---

config.json
exercises/practice/diamond/.docs/instructions.md
exercises/practice/diamond/.meta/config.json
exercises/practice/diamond/.meta/example.cpp
exercises/practice/diamond/.meta/example.h
exercises/practice/diamond/.meta/tests.toml
exercises/practice/diamond/CMakeLists.txt
exercises/practice/diamond/diamond.cpp
exercises/practice/diamond/diamond.h
exercises/practice/diamond/diamond_test.cpp
exercises/practice/diamond/test/catch.hpp
exercises/practice/diamond/test/tests-main.cpp

Another exercise from https://gist.github.com/ErikSchierboom/2f121db2bc55003129408edcd19183dc

feat: add diamond exercise

---

exercises/concept/ellens-alien-game/ellens_alien_game_test.cpp

https://forum.exercism.org/t/ellens-alien-game-c-why-task-1-fails/9150/3

fix(concepts): correct task grouping in alien game

---

exercises/practice/reverse-string/.approaches/config.json
exercises/practice/reverse-string/.approaches/direct-construction/content.md
exercises/practice/reverse-string/.approaches/direct-construction/snippet.txt
exercises/practice/reverse-string/.approaches/divide-and-conquer/content.md
exercises/practice/reverse-string/.approaches/divide-and-conquer/snippet.txt
exercises/practice/reverse-string/.approaches/introduction.md
exercises/practice/reverse-string/.approaches/iterative/content.md
exercises/practice/reverse-string/.approaches/iterative/snippet.txt
exercises/practice/reverse-string/.approaches/linear-recursion/content.md
exercises/practice/reverse-string/.approaches/linear-recursion/snippet.txt
exercises/practice/reverse-string/.approaches/over-engineered/content.md
exercises/practice/reverse-string/.approaches/over-engineered/snippet.txt
exercises/practice/reverse-string/.approaches/stack-operations/content.md
exercises/practice/reverse-string/.approaches/stack-operations/snippet.txt
exercises/practice/reverse-string/.approaches/swapping-characters/content.md
exercises/practice/reverse-string/.approaches/swapping-characters/snippet.txt
exercises/practice/reverse-string/.approaches/using-the-standard-lib/content.md
exercises/practice/reverse-string/.approaches/using-the-standard-lib/snippet.txt

Please feel free to critize anything, big-picture issue and small nitpicks.

Write "approaches" for reverse-string

---

exercises/practice/leap/.docs/introduction.md
exercises/practice/leap/.meta/config.json

Sync the `leap` exercise with the latest data, as defined in https://github.com/exercism/problem-specifications/tree/main/exercises/leap.

leap: sync

---

exercises/concept/doctor-data/.docs/instructions.md
exercises/concept/doctor-data/doctor_data.cpp
exercises/concept/doctor-data/doctor_data.h

Let's make it more obvious: https://forum.exercism.org/t/doctor-data-c-strange-text/9340

feat: make corrupted files more explicit for doctor-data

---

exercises/concept/doctor-data/doctor_data_test.cpp

fix(concepts): correct task grouping in doctor data

---

config.json
exercises/practice/knapsack/.docs/instructions.md
exercises/practice/knapsack/.meta/config.json
exercises/practice/knapsack/.meta/create_tests.py
exercises/practice/knapsack/.meta/example.cpp
exercises/practice/knapsack/.meta/example.h
exercises/practice/knapsack/.meta/tests.toml
exercises/practice/knapsack/CMakeLists.txt
exercises/practice/knapsack/knapsack.cpp
exercises/practice/knapsack/knapsack.h
exercises/practice/knapsack/knapsack_test.cpp
exercises/practice/knapsack/test/catch.hpp
exercises/practice/knapsack/test/tests-main.cpp

All feedback and criticism welcome.

Add exercise 'knapsack'.

---

exercises/concept/log-levels/log_levels.cpp

feat: add skeleton to log exercise stub

---

exercises/practice/complex-numbers/.meta/example.cpp
exercises/practice/complex-numbers/.meta/example.h
exercises/practice/complex-numbers/.meta/tests.toml
exercises/practice/complex-numbers/complex_numbers_test.cpp

Updated Tests according to the Specification

Update Tests based on the Problem Specification

---

exercises/practice/pangram/.meta/tests.toml
exercises/practice/pangram/pangram_test.cpp

Related to #775. Please mark `rep/tiny`. :)

Sync pangram tests

---

exercises/practice/isogram/.meta/tests.toml
exercises/practice/isogram/isogram_test.cpp

For #775. Please mark `rep/tiny`. :)

Sync isogram tests

---

concepts/switch/introduction.md

concept switch: fix typo

---

concepts/functions/introduction.md
exercises/concept/lasagna-master/.docs/introduction.md

Fix a small typo in introduction.md for the lasagna-master exercise.

Fix typo: lenghth --> length.

---

exercises/concept/making-the-grade/.docs/instructions.md

docs: add instructions for calculating grade intervals

---

exercises/concept/speedywagon/speedywagon_test.cpp

the code does not compile otherwise - neither in the web ui nor locally
thanks to Manuel Grobbauer for pointing this out

fixed missing closing tag for testcase

---

exercises/concept/power-of-troy/.docs/instructions.md
exercises/concept/power-of-troy/.docs/introduction.md
exercises/concept/power-of-troy/.meta/exemplar.h
exercises/concept/power-of-troy/power_of_troy.h

I added some clarifications and made it easier to understand when using non-c++ 20 compilers, like the test runner...

fix: make smart-pointer exercise easier

---

exercises/concept/making-the-grade/.docs/hints.md
exercises/concept/making-the-grade/.docs/instructions.md
exercises/concept/making-the-grade/.meta/exemplar.cpp
exercises/concept/making-the-grade/making_the_grade.cpp
exercises/concept/making-the-grade/making_the_grade_test.cpp

This PR removes task 3 as it does not teach anything that was not already taught in part 1.
I will probably move part 4 and 5 and put them in a range based for loop exercise.

feat: remove part 3 from making the grade

---

exercises/concept/troll-the-trolls/.docs/introduction.md

Fixed a typo in the readme of "Troll the Trolls".

fixed typo

---

exercises/concept/speedywagon/.docs/introduction.md

fix: remove delete instruction
